// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyC9n0NXeSPtXqpCf28Azpb1RrKQS3afjjI",
  authDomain: "recipetestappflutter.firebaseapp.com",
  projectId: "recipetestappflutter",
  storageBucket: "recipetestappflutter.appspot.com",
  messagingSenderId: "904284152639",
  appId: "1:904284152639:web:ab007ee6dfba57ae3c298a"
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: "AIzaSyC9n0NXeSPtXqpCf28Azpb1RrKQS3afjjI",
  authDomain: "recipetestappflutter.firebaseapp.com",
  projectId: "recipetestappflutter",
  storageBucket: "recipetestappflutter.appspot.com",
  messagingSenderId: "904284152639",
  appId: "1:904284152639:web:ab007ee6dfba57ae3c298a"
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: "AIzaSyC9n0NXeSPtXqpCf28Azpb1RrKQS3afjjI",
  authDomain: "recipetestappflutter.firebaseapp.com",
  projectId: "recipetestappflutter",
  storageBucket: "recipetestappflutter.appspot.com",
  messagingSenderId: "904284152639",
  appId: "1:904284152639:web:ab007ee6dfba57ae3c298a"
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: "AIzaSyC9n0NXeSPtXqpCf28Azpb1RrKQS3afjjI",
  authDomain: "recipetestappflutter.firebaseapp.com",
  projectId: "recipetestappflutter",
  storageBucket: "recipetestappflutter.appspot.com",
  messagingSenderId: "904284152639",
  appId: "1:904284152639:web:ab007ee6dfba57ae3c298a"
  );
}